//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HospitalDBContext : DbContext
    {
        public HospitalDBContext()
            : base("name=HospitalDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_MstHospital> tbl_MstHospital { get; set; }
    
        public virtual ObjectResult<sp_SearchHospital_Result> sp_SearchHospital(string searchKeyWord)
        {
            var searchKeyWordParameter = searchKeyWord != null ?
                new ObjectParameter("SearchKeyWord", searchKeyWord) :
                new ObjectParameter("SearchKeyWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchHospital_Result>("sp_SearchHospital", searchKeyWordParameter);
        }
    
        public virtual ObjectResult<tbl_MstHospital> SearchHospital(string searchKeyWord)
        {
            var searchKeyWordParameter = searchKeyWord != null ?
                new ObjectParameter("SearchKeyWord", searchKeyWord) :
                new ObjectParameter("SearchKeyWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_MstHospital>("SearchHospital", searchKeyWordParameter);
        }
    
        public virtual ObjectResult<tbl_MstHospital> SearchHospital(string searchKeyWord, MergeOption mergeOption)
        {
            var searchKeyWordParameter = searchKeyWord != null ?
                new ObjectParameter("SearchKeyWord", searchKeyWord) :
                new ObjectParameter("SearchKeyWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_MstHospital>("SearchHospital", mergeOption, searchKeyWordParameter);
        }
    }
}
